# Generated by Django 3.0.4 on 2020-04-12 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('admins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminreason',
            name='banneduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BannedUser'),
        ),
        migrations.AddField(
            model_name='adminreason',
            name='reportedadmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.ReportedAdmin'),
        ),
        migrations.AddField(
            model_name='adminparent',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator+', to=settings.AUTH_USER_MODEL),
        ),
    ]
