# Generated by Django 3.0.4 on 2020-04-12 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReportedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('bookadder', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookadder+', to='books.Book')),
                ('deleterequest', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleterequest+', to='books.DeleteBookRequest')),
                ('issue', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue+', to='issues.Issue')),
                ('reporting_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_admin+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('creation_date', models.DateTimeField(verbose_name='creation_date')),
                ('gender', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateTimeField(verbose_name='date_of_birth')),
                ('country', models.CharField(max_length=20)),
                ('email', models.EmailField(default='google.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('banneduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BannedUser')),
                ('reporteduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ReportedUser')),
            ],
        ),
    ]
